MCU = RP2040
BOOTLOADER = rp2040

# Feature flags
DYNAMIC_MACRO_ENABLE = yes
UNICODE_COMMON = yes
AUTOCORRECT_ENABLE = yes
EXTRAKEY_ENABLE = yes

# Split
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor

CONSOLE_ENABLE = yes
