// Split
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_PIN_SWAP
#define SERIAL_USART_TX_PIN GP4
#define SERIAL_USART_RX_PIN GP1
#define MASTER_RIGHT
#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX

// Encoders
#define ENCODER_A_PINS { GP29 }
#define ENCODER_B_PINS { GP28 }
#define ENCODER_A_PINS_RIGHT { GP29 }
#define ENCODER_B_PINS_RIGHT { GP28 }

// OLED
#define I2C1_SCL_PIN GP3
#define I2C1_SDA_PIN GP2
#define OLED_DISPLAY_128X64
#define SPLIT_LAYER_STATE_ENABLE

// debug
#define SERIAL_DEBUG

#define HOLD_ON_OTHER_KEY_PRESS
