MCU = RP2040
BOOTLOADER = rp2040

DYNAMIC_MACRO_ENABLE = yes
AUTOCORRECT_ENABLE = yes
TRI_LAYER_ENABLE = yes
EXTRAKEY_ENABLE = yes
UNICODE_COMMON = yes
WPM_ENABLE = yes

# Split
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor

# Encoders
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

# OLED
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c
SRC += bongo.c

# Debug
CONSOLE_ENABLE = yes

